/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sematext.spm.client.tracing.thrift;


import org.apache.thrift.TEnum;

public enum TCallTag implements TEnum {
  REGULAR(0),
  SQL_QUERY(1),
  EXTERNAL(2),
  JPA(3),
  JSP(4),
  HTTP_REQUEST(5),
  ES(6),
  SOLR(7);

  private final int value;

  private TCallTag(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TCallTag findByValue(int value) { 
    switch (value) {
      case 0:
        return REGULAR;
      case 1:
        return SQL_QUERY;
      case 2:
        return EXTERNAL;
      case 3:
        return JPA;
      case 4:
        return JSP;
      case 5:
        return HTTP_REQUEST;
      case 6:
        return ES;
      case 7:
        return SOLR;
      default:
        return null;
    }
  }
}
