/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sematext.spm.client.tracing.thrift;


import org.apache.thrift.TEnum;

public enum TESOperationType implements TEnum {
  INDEX(0),
  DELETE(1),
  SEARCH(2),
  GET(3),
  UPDATE(4);

  private final int value;

  private TESOperationType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TESOperationType findByValue(int value) { 
    switch (value) {
      case 0:
        return INDEX;
      case 1:
        return DELETE;
      case 2:
        return SEARCH;
      case 3:
        return GET;
      case 4:
        return UPDATE;
      default:
        return null;
    }
  }
}
