/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sematext.spm.client.tracing.thrift;


import org.apache.thrift.TEnum;

public enum TESRequestType implements TEnum {
  INDEX_BULK(0),
  UPDATE_BULK(1),
  DELETE_BULK(2),
  BULK(3),
  INDEX(4),
  DELETE(5),
  SEARCH(6),
  GET(7),
  UPDATE(8);

  private final int value;

  private TESRequestType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TESRequestType findByValue(int value) { 
    switch (value) {
      case 0:
        return INDEX_BULK;
      case 1:
        return UPDATE_BULK;
      case 2:
        return DELETE_BULK;
      case 3:
        return BULK;
      case 4:
        return INDEX;
      case 5:
        return DELETE;
      case 6:
        return SEARCH;
      case 7:
        return GET;
      case 8:
        return UPDATE;
      default:
        return null;
    }
  }
}
