/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sematext.spm.client.tracing.thrift;


import org.apache.thrift.TEnum;

public enum TFailureType implements TEnum {
  EXCEPTION(0),
  HTTP_RESPONSE(1),
  CUSTOM(2);

  private final int value;

  private TFailureType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TFailureType findByValue(int value) { 
    switch (value) {
      case 0:
        return EXCEPTION;
      case 1:
        return HTTP_RESPONSE;
      case 2:
        return CUSTOM;
      default:
        return null;
    }
  }
}
