/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sematext.spm.client.tracing.thrift;


import org.apache.thrift.TEnum;

public enum TSolrRequestType implements TEnum {
  SCHEMA(0),
  UPDATE(1),
  COLLECTION_ADMIN(2),
  CORE_ADMIN(3),
  ANALYSIS(4),
  QUERY(5),
  OTHER(6);

  private final int value;

  private TSolrRequestType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TSolrRequestType findByValue(int value) { 
    switch (value) {
      case 0:
        return SCHEMA;
      case 1:
        return UPDATE;
      case 2:
        return COLLECTION_ADMIN;
      case 3:
        return CORE_ADMIN;
      case 4:
        return ANALYSIS;
      case 5:
        return QUERY;
      case 6:
        return OTHER;
      default:
        return null;
    }
  }
}
