/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sematext.spm.client.tracing.thrift;


import org.apache.thrift.TEnum;

public enum TSqlStatementOperation implements TEnum {
  SELECT(0),
  DELETE(1),
  UPDATE(2),
  INSERT(3),
  OTHER(4);

  private final int value;

  private TSqlStatementOperation(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TSqlStatementOperation findByValue(int value) { 
    switch (value) {
      case 0:
        return SELECT;
      case 1:
        return DELETE;
      case 2:
        return UPDATE;
      case 3:
        return INSERT;
      case 4:
        return OTHER;
      default:
        return null;
    }
  }
}
